[build]
  command = "npm install"
  publish = "public"
  functions = "netlify/functions"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/api/api/:splat"
  status = 200

[[redirects]]
  from = "/api"
  to = "/.netlify/functions/api/api"
  status = 200
